FROM ubuntu:bionic

ARG VENV_DIR=/venv
#ARG PIP_EXEC=$VENV_DIR/bin/pip3

RUN apt-get update && apt-get install -y \
    python3 python3-pip python3-pytest\
    libgconf2-4 libnss3 libxss1 \
    fonts-liberation libappindicator1 xdg-utils \
    software-properties-common \
    curl unzip wget \
    xvfb

# install google chrome
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
RUN apt-get -y update
RUN apt-get install -y google-chrome-stable

COPY requirements.txt .

RUN pip3 install --upgrade pip #&& \
#    pip3 install virtualenv
RUN pip3 install allure-pytest
#RUN pip3 install selenium
#RUN pip3 install chromedriver-binary
#RUN pip3 install webdriver-manager
#RUN virtualenv -p python3.6 $VENV_DIR
#RUN pip3 install chromedriver-autoinstaller
RUN pip3 install  -r requirements.txt
RUN apt-get install -yqq unzip
RUN apt-get install -y google-chrome-stable
RUN wget -O /tmp/chromedriver.zip http://chromedriver.storage.googleapis.com/`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE`/chromedriver_linux64.zip
RUN unzip /tmp/chromedriver.zip chromedriver -d /usr/local/bin/
#RUN echo $VIRTUAL_ENV

#RUN bin/bash -c "source $VENV_DIR/bin/activate"

#RUN . $VENV_DIR/bin/activate

#RUN source deactivate
#RUN virtualenv $VENV_DIR
#RUN bin/bash -c "source  $VENV_DIR/bin/activate"

#RUN echo $VIRTUAL_ENV

ENV APP_HOME /usr/src/app
WORKDIR $APP_HOME
COPY . $APP_HOME

ENV ALLURE_FOLDER_CHROME /result
ENV TEST_HOST https://testingqa.payform.ru/
ENV BROWSER chrome
ENV DISPLAY=:0
VOLUME $ALLURE_FOLDER_CHROME

CMD ./run.sh --alluredir=/$ALLURE_FOLDER_CHROME